# -*- coding: utf-8 -*-
"""mvp_webscrap.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UP7kq0rnpY0T9T9z1Z-4-9pqQm-k0eQc
"""

import pandas as pd
import requests as req
from bs4 import BeautifulSoup

import gspread
from google.oauth2.service_account import Credentials
import os
import openpyxl as opyxl
from datetime import datetime

import requests as req
from bs4 import BeautifulSoup
import pandas as pd
from datetime import datetime
import gspread
from oauth2client.service_account import ServiceAccountCredentials
import json

# === SCRAPING ===
url = "https://www.bna.com.ar/Personas"
req_response = req.get(url)

if req_response.status_code == 200:
    soup = BeautifulSoup(req_response.content, "html.parser")

    for tr_element in soup.find_all("tr"):
        if tr_element.td and "Dolar U.S.A" in tr_element.td.text:
            moneda_compra_venta = tr_element.find_all("td", limit=3)
            dolar_dic = {
                "moneda": moneda_compra_venta[0].text.strip(),
                "compra": moneda_compra_venta[1].text.strip().replace(',', '.'),
                "venta": moneda_compra_venta[2].text.strip().replace(',', '.')
            }
            break
else:
    raise Exception("Error al hacer scraping")

# === CONEXIÓN CON GOOGLE SHEETS ===
scope = ["https://spreadsheets.google.com/feeds", "https://www.googleapis.com/auth/drive"]
#credenciales = ServiceAccountCredentials.from_json_keyfile_name("credenciales.json", scope)
#cliente = gspread.authorize(credenciales)

credenciales_json = os.environ["GOOGLE_CREDENTIALS"]
credenciales_dict = json.loads(credenciales_json)
credenciales = ServiceAccountCredentials.from_json_keyfile_dict(credenciales_dict, scope)

gc = gspread.authorize(credenciales)

# Abre la hoja
spreadsheet = cliente.open_by_key("1jio09_eyPVeRk5ass-YV8eBouMIjLY8PTDAUq9xu-ts")
hoja = spreadsheet.worksheet("Scrap")

# Encuentra la primera fila vacía (en columna F)
fila = 3  # Asumimos que la fila 1 es encabezado
while hoja.cell(fila, 6).value:  # Columna F es la columna 6
    fila += 1

# Escribimos en columnas F, G y J (6, 7 y 10)
fecha = datetime.now().strftime("%Y-%m-%d")
hoja.update_cell(fila, 6, fecha)              # F - Fecha
hoja.update_cell(fila, 7, dolar_dic["venta"]) # G - Venta
hoja.update_cell(fila, 10, dolar_dic["compra"])  # J - Compra
