name: Ejecutar scraper cada 15 minutos desde 13:00 AR

on:
  schedule:
    - cron: '0,15,30,45 16-23 * * *'  # Corre cada 15 minutos de 13:00 a 20:45 AR (16:00 a 23:45 UTC)
  workflow_dispatch:  # También permite correrlo manualmente desde GitHub

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repo
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ejecutar scraper
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      run: |
        python mvp_webscrap.py
